FROM daskgateway/dask-gateway:0.9.0

# Documentation: https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html

RUN conda install --yes -c conda-forge -n base coffea python-graphviz mimesis