# Documentation: https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html
FROM pangeo/base-notebook:2020.11.06
RUN conda install --yes -c conda-forge -n notebook nb_conda_kernels coffea python-graphviz mimesis
